apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpeserverprofiletemplates.infra.hpe.com
spec:
  group: infra.hpe.com
  names:
    kind: HPEServerProfileTemplate
    listKind: HPEServerProfileTemplateList
    plural: hpeserverprofiletemplates
    singular: hpeserverprofiletemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HPEServerProfileTemplate is the Schema for the hpeserverprofiletemplates
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of HPEServerProfileTemplate
            properties:
              bios:
                properties:
                  complianceControl:
                    type: string
                  manageBios:
                    type: boolean
                  overriddenSettings:
                    items:
                      properties:
                        id:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                required:
                - complianceControl
                - manageBios
                - overriddenSettings
                type: object
              bootMode:
                properties:
                  complianceControl:
                    type: string
                  manageMode:
                    type: boolean
                  mode:
                    type: string
                  pxeBootPolicy:
                    type: string
                  secureBoot:
                    type: string
                required:
                - complianceControl
                - manageMode
                - mode
                - pxeBootPolicy
                - secureBoot
                type: object
              firmware:
                properties:
                  complianceControl:
                    enum:
                    - Checked
                    - UnChecked
                    type: string
                  firmwareActivationType:
                    type: string
                  firmwareBaselineUri:
                    type: string
                  firmwareInstallType:
                    type: string
                  installationPolicy:
                    enum:
                    - LowerThanBaseline
                    - NotEqualToBaseline
                    type: string
                  manageFirmware:
                    type: boolean
                required:
                - manageFirmware
                - firmwareBaselineUri
                - installationPolicy
                - complianceControl
                - firmwareInstallType
                - firmwareActivationType
                type: object
              hardwareType:
                enum:
                - DL360 Gen11
                - DL365 Gen11
                type: string
              localStorage:
                properties:
                  complianceControl:
                    type: string
                  controllers:
                    items:
                      properties:
                        deviceSlot:
                          type: string
                        family:
                          type: string
                        initialize:
                          type: boolean
                        logicalDrives:
                          items:
                            properties:
                              bootable:
                                type: boolean
                              name:
                                type: string
                              numPhysicalDrives:
                                type: integer
                              raidLevel:
                                type: string
                            type: object
                          type: array
                        mode:
                          type: string
                      type: object
                    type: array
                required:
                - controllers
                - complianceControl
                type: object
            required:
            - hardwareType
            type: object
            x-kubernetes-preserve-unknown-fields: true
            x-kubernetes-validations:
            - message: At least one of bios, localStorage, bootMode or firmware must
                be specified
              rule: has(self.bios) || has(self.localStorage) || has(self.bootMode)
                || has(self.firmware)
          status:
            description: Status defines the observed state of HPEServerProfileTemplate
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
        x-kubernetes-validations:
        - message: 'The ''spec'' field is mandatory. The ''spec'' field must include:
            hardwareType (required), bios (optional), localStorage (optional), bootMode
            (optional), firmware (optional).'
          rule: has(self.spec)
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
