apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: hpeoneview-operator
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: hpeoneview-operator
  name: hpeoneview-operator-webhook-service
spec:
  ports:
  - port: 5060
    protocol: TCP
    targetPort: 5060
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
