apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpeserverprofiles.infra.hpe.com
spec:
  group: infra.hpe.com
  names:
    kind: HPEServerProfile
    listKind: HPEServerProfileList
    plural: hpeserverprofiles
    singular: hpeserverprofile
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HPEServerProfile is the Schema for the hpeserverprofiles API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of HPEServerProfile
            properties:
              serverName:
                type: string
              serverProfileTemplate:
                type: string
            required:
            - serverProfileTemplate
            - serverName
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of HPEServerProfile
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
        x-kubernetes-validations:
        - message: 'The ''spec'' field is mandatory. The ''spec'' field must include:
            serverProfileTemplate (required), serverName (required).'
          rule: has(self.spec)
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
